version: "3.8"

services:
  php:
    build: ./docker/php
    working_dir: /var/www/project
    volumes:
      # Comment out the next line in production
      - ./:/var/www/project:rw,cached
      # If you develop on Linux, comment out the following volumes to just use bind-mounted project directory from host
      - /var/www/project/var/
      - /var/www/project/var/cache/
      - /var/www/project/var/logs/
      - /var/www/project/var/sessions/

  nginx:
    image: nginx:1.19
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./:/var/www/project/"

  mariadb:
    image: mariadb:10.5.5
    volumes:
      - ./docker/data/mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cleanapp
      MYSQL_USER: cleanapp
      MYSQL_PASSWORD: cleanapp
