App\Domain\Entity\Issue:
  type: entity
  table: issues

  id:
    id:
      type: integer
      generator:
        strategy: AUTO

  fields:
    title:
      type: string

    content:
      type: text

  manyToOne:
    createdBy:
      targetEntity: App\Domain\Entity\User
      inversedBy: issues
      joinColumn:
        name: created_by_id
        referencedColumnName: id
